/*
	List of countries, with:
		- Conversion factor
		- Protein consumption
		- Bod per day 

		Albania
		Algeria
		Angola
		Antigua and Barbuda
		Argentina
		Armenia
		Australia
		Austria
		Azerbaijan
		Bahamas
		Bangladesh
		Barbados
		Belarus
		Belgium
		Belize
		Benin
		Bermuda
		Bolivia (Plurinational State of)
		Bosnia and Herzegovina
		Botswana
		Brazil
		Brunei Darussalam
		Bulgaria
		Burkina Faso
		Burundi
		Cambodia
		Cameroon
		Canada
		Cape Verde
		Central African Republic
		Chad
		Chile
		China
		Colombia
		Comoros
		Congo
		Costa Rica
		Côte d'Ivoire
		Croatia
		Cuba
		Cyprus
		Czech Republic
		Democratic People's Republic of Korea
		Denmark
		Djibouti
		Dominica
		Dominican Republic
		Ecuador
		Egypt
		El Salvador
		Eritrea
		Estonia
		Ethiopia
		Fiji
		Finland
		France
		French Polynesia
		Gabon
		Gambia
		Georgia
		Germany
		Ghana
		Greece
		Grenada
		Guatemala
		Guinea
		Guinea-Bissau
		Guyana
		Haiti
		Honduras
		Hungary
		Iceland
		India
		Indonesia
		Iran (Islamic Republic of)
		Ireland
		Israel
		Italy
		Jamaica
		Japan
		Jordan
		Kazakhstan
		Kenya
		Kiribati
		Kuwait
		Kyrgyzstan
		Lao People's Democratic Republic
		Latvia
		Lebanon
		Lesotho
		Liberia
		Libyan Arab Jamahiriya
		Lithuania
		Luxembourg
		Madagascar
		Malawi
		Malaysia
		Maldives
		Mali
		Malta
		Mauritania
		Mauritius
		Mexico
		Mongolia
		Morocco
		Mozambique
		Namibia
		Nepal
		Netherlands
		Netherlands Antilles
		New Caledonia
		New Zealand
		Nicaragua
		Niger
		Nigeria
		Norway
		Occupied Palestinian Territory
		Pakistan
		Panama
		Paraguay
		Peru
		Philippines
		Poland
		Portugal
		Republic of Korea
		Republic of Moldova
		Romania
		Russian Federation
		Rwanda
		Saint Kitts and Nevis
		Saint Lucia
		Saint Vincent and the Grenadines
		Samoa
		Sao Tome and Principe
		Saudi Arabia
		Senegal
		Serbia and Montenegro
		Seychelles
		Sierra Leone
		Slovakia
		Slovenia
		Solomon Islands
		South Africa
		Spain
		Sri Lanka
		Sudan
		Suriname
		Swaziland
		Sweden
		Switzerland
		Syrian Arab Republic
		Tajikistan
		Thailand
		The former Yugoslav Republic of Macedonia
		Timor-Leste
		Togo
		Trinidad and Tobago
		Tunisia
		Turkey
		Turkmenistan
		Uganda
		Ukraine
		United Arab Emirates
		United Kingdom
		United Republic of Tanzania
		United States of America
		Uruguay
		Uzbekistan
		Vanuatu
		Venezuela (Bolivarian Republic of)
		Viet Nam
		Yemen
		Zambia
		Zimbabwe
*/

var Countries={
	"Albania":{
		wwc_prot_con:36.135,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Algeria":{
		wwc_prot_con:31.39,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Angola":{
		wwc_prot_con:15.695,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Antigua and Barbuda":{
		wwc_prot_con:29.93,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Argentina":{
		wwc_prot_con:34.31,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Armenia":{
		wwc_prot_con:25.55,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Australia":{
		wwc_prot_con:38.69,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Austria":{
		wwc_prot_con:39.055,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Azerbaijan":{
		wwc_prot_con:31.39,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bahamas":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bangladesh":{
		wwc_prot_con:17.885,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Barbados":{
		wwc_prot_con:34.675,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Belarus":{
		wwc_prot_con:32.485,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Belgium":{
		wwc_prot_con:35.405,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Belize":{
		wwc_prot_con:26.28,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Benin":{
		wwc_prot_con:21.535,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bermuda":{
		wwc_prot_con:27.74,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bolivia (Plurinational State of)":{
		wwc_prot_con:20.44,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bosnia and Herzegovina":{
		wwc_prot_con:32.12,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Botswana":{
		wwc_prot_con:23.36,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Brazil":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Brunei Darussalam":{
		wwc_prot_con:31.755,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Bulgaria":{
		wwc_prot_con:28.105,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Burkina Faso":{
		wwc_prot_con:29.2,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Burundi":{
		wwc_prot_con:16.425,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Cambodia":{
		wwc_prot_con:20.805,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Cameroon":{
		wwc_prot_con:21.17,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Canada":{
		wwc_prot_con:38.325,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Cape Verde":{
		wwc_prot_con:24.82,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Central African Republic":{
		wwc_prot_con:16.79,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Chad":{
		wwc_prot_con:22.63,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Chile":{
		wwc_prot_con:32.12,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"China":{
		wwc_prot_con:32.485,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Colombia":{
		wwc_prot_con:23.725,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Comoros":{
		wwc_prot_con:16.06,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Congo":{
		wwc_prot_con:19.345,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Costa Rica":{
		wwc_prot_con:27.01,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Côte d'Ivoire":{
		wwc_prot_con:18.25,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Croatia":{
		wwc_prot_con:28.835,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Cuba":{
		wwc_prot_con:29.2,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Cyprus":{
		wwc_prot_con:35.04,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Czech Republic":{
		wwc_prot_con:35.04,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Democratic People's Republic of Korea":{
		wwc_prot_con:21.17,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Denmark":{
		wwc_prot_con:40.515,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Djibouti":{
		wwc_prot_con:21.17,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Dominica":{
		wwc_prot_con:33.945,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Dominican Republic":{
		wwc_prot_con:18.98,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Ecuador":{
		wwc_prot_con:20.805,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Egypt":{
		wwc_prot_con:33.215,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"El Salvador":{
		wwc_prot_con:25.915,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Eritrea":{
		wwc_prot_con:17.155,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Estonia":{
		wwc_prot_con:33.215,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Ethiopia":{
		wwc_prot_con:20.44,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Fiji":{
		wwc_prot_con:28.835,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Finland":{
		wwc_prot_con:39.055,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"France":{
		wwc_prot_con:41.245,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"French Polynesia":{
		wwc_prot_con:36.5,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Gabon":{
		wwc_prot_con:29.565,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Gambia":{
		wwc_prot_con:20.075,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Georgia":{
		wwc_prot_con:28.105,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Germany":{
		wwc_prot_con:36.135,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Ghana":{
		wwc_prot_con:21.535,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Greece":{
		wwc_prot_con:43.07,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Grenada":{
		wwc_prot_con:27.01,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Guatemala":{
		wwc_prot_con:20.805,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Guinea":{
		wwc_prot_con:19.71,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Guinea-Bissau":{
		wwc_prot_con:16.06,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Guyana":{
		wwc_prot_con:27.375,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Haiti":{
		wwc_prot_con:14.965,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Honduras":{
		wwc_prot_con:24.455,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Hungary":{
		wwc_prot_con:32.485,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Iceland":{
		wwc_prot_con:48.545,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"India":{
		wwc_prot_con:20.44,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Indonesia":{
		wwc_prot_con:20.44,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Iran (Islamic Republic of)":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Ireland":{
		wwc_prot_con:40.15,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Israel":{
		wwc_prot_con:45.99,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Italy":{
		wwc_prot_con:40.88,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Jamaica":{
		wwc_prot_con:28.47,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Japan":{
		wwc_prot_con:33.58,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Jordan":{
		wwc_prot_con:27.74,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Kazakhstan":{
		wwc_prot_con:37.96,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Kenya":{
		wwc_prot_con:21.17,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Kiribati":{
		wwc_prot_con:27.01,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Kuwait":{
		wwc_prot_con:33.945,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Kyrgyzstan":{
		wwc_prot_con:30.295,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Lao People's Democratic Republic":{
		wwc_prot_con:22.265,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Latvia":{
		wwc_prot_con:32.12,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Lebanon":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Lesotho":{
		wwc_prot_con:25.185,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Liberia":{
		wwc_prot_con:13.14,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Libyan Arab Jamahiriya":{
		wwc_prot_con:28.105,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Lithuania":{
		wwc_prot_con:41.975,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Luxembourg":{
		wwc_prot_con:44.895,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Madagascar":{
		wwc_prot_con:17.885,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Malawi":{
		wwc_prot_con:20.075,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Malaysia":{
		wwc_prot_con:28.835,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Maldives":{
		wwc_prot_con:40.15,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mali":{
		wwc_prot_con:25.915,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Malta":{
		wwc_prot_con:43.07,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mauritania":{
		wwc_prot_con:31.39,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mauritius":{
		wwc_prot_con:30.295,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mexico":{
		wwc_prot_con:33.58,
		conv_kwh_co2:0.452483345,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mongolia":{
		wwc_prot_con:26.28,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Morocco":{
		wwc_prot_con:32.485,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Mozambique":{
		wwc_prot_con:13.87,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Namibia":{
		wwc_prot_con:24.455,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Nepal":{
		wwc_prot_con:21.9,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Netherlands":{
		wwc_prot_con:38.325,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Netherlands Antilles":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"New Caledonia":{
		wwc_prot_con:31.025,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"New Zealand":{
		wwc_prot_con:34.31,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Nicaragua":{
		wwc_prot_con:22.63,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Niger":{
		wwc_prot_con:27.01,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Nigeria":{
		wwc_prot_con:22.63,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Norway":{
		wwc_prot_con:39.055,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Occupied Palestinian Territory":{
		wwc_prot_con:21.535,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Pakistan":{
		wwc_prot_con:20.805,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Panama":{
		wwc_prot_con:25.915,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Paraguay":{
		wwc_prot_con:25.55,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Peru":{
		wwc_prot_con:24.455,
		conv_kwh_co2:0.237721212,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Philippines":{
		wwc_prot_con:21.535,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Poland":{
		wwc_prot_con:36.865,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Portugal":{
		wwc_prot_con:41.61,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Republic of Korea":{
		wwc_prot_con:32.12,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Republic of Moldova":{
		wwc_prot_con:28.105,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Romania":{
		wwc_prot_con:40.515,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Russian Federation":{
		wwc_prot_con:35.405,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Rwanda":{
		wwc_prot_con:17.885,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Saint Kitts and Nevis":{
		wwc_prot_con:26.28,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Saint Lucia":{
		wwc_prot_con:33.945,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Saint Vincent and the Grenadines":{
		wwc_prot_con:28.835,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Samoa":{
		wwc_prot_con:27.74,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Sao Tome and Principe":{
		wwc_prot_con:21.9,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Saudi Arabia":{
		wwc_prot_con:31.755,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Senegal":{
		wwc_prot_con:21.535,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Serbia and Montenegro":{
		wwc_prot_con:27.375,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Seychelles":{
		wwc_prot_con:30.66,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Sierra Leone":{
		wwc_prot_con:18.98,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Slovakia":{
		wwc_prot_con:26.645,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Slovenia":{
		wwc_prot_con:36.865,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Solomon Islands":{
		wwc_prot_con:19.345,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"South Africa":{
		wwc_prot_con:29.565,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Spain":{
		wwc_prot_con:39.42,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Sri Lanka":{
		wwc_prot_con:20.075,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Sudan":{
		wwc_prot_con:26.645,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Suriname":{
		wwc_prot_con:20.075,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Swaziland":{
		wwc_prot_con:22.995,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Sweden":{
		wwc_prot_con:39.055,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Switzerland":{
		wwc_prot_con:33.58,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Syrian Arab Republic":{
		wwc_prot_con:29.2,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Tajikistan":{
		wwc_prot_con:19.71,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Thailand":{
		wwc_prot_con:20.805,
		conv_kwh_co2:0.626742612,
		wwc_bod_pday:40,
		gwp:0,
	},
	"The former Yugoslav Republic of Macedonia":{
		wwc_prot_con:27.74,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Timor-Leste":{
		wwc_prot_con:18.25,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Togo":{
		wwc_prot_con:17.885,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Trinidad and Tobago":{
		wwc_prot_con:24.82,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Tunisia":{
		wwc_prot_con:33.945,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Turkey":{
		wwc_prot_con:36.135,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Turkmenistan":{
		wwc_prot_con:31.755,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Uganda":{
		wwc_prot_con:17.885,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Ukraine":{
		wwc_prot_con:32.485,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"United Arab Emirates":{
		wwc_prot_con:37.96,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"United Kingdom":{
		wwc_prot_con:37.96,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"United Republic of Tanzania":{
		wwc_prot_con:18.25,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"United States of America":{
		wwc_prot_con:41.61,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Uruguay":{
		wwc_prot_con:29.2,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Uzbekistan":{
		wwc_prot_con:27.375,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Vanuatu":{
		wwc_prot_con:23.36,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Venezuela (Bolivarian Republic of)":{
		wwc_prot_con:25.915,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Viet Nam":{
		wwc_prot_con:26.28,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Yemen":{
		wwc_prot_con:19.71,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Zambia":{
		wwc_prot_con:17.52,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
	"Zimbabwe":{
		wwc_prot_con:20.075,
		conv_kwh_co2:0,
		wwc_bod_pday:40,
		gwp:0,
	},
};

